name: Pull Requests Check

on:
  pull_request:
    branches: [ main ]

jobs:
  pull-requests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3
          arguments: build