name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3
          arguments: build

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - uses: actions/upload-artifact@v2
        with:
          path: build/libs
          if-no-files-found: error

  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'development'
    concurrency: development
    needs: build
    steps:
      - name: Deploy development
        run: echo Hello, world!

  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    concurrency: prod
    needs: [ build,deploy-dev ]
    steps:
      - name: Deploy prod
        run: echo Hello, world!